# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yuanruiyang's Blog
email: yuanry9801@163.com
description: > # this means to ignore newlines until "baseurl:"
  搭建博客，养成好的学习、研究习惯，记录自己的学习点滴，每天进步一点点，天天向上！Doing is better than perfect!!!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Rain9801
github_username:  Rain9801

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight
